### ISSUE TITLE
Checking the error for the length of MC samples

### ISSUE THREAD

**Issue by sivaramakrishnan-rajaraman** [seedatnabeel/Uncertainty-Decision-Support-Healthcare#2]
Hi, Nabeel,
Could you please explain what the following lines do? I am not clear what '13' represents here. There are six Monte Carlo samples for which you evaluate the uncertainty (3, 5, 10, 15, 20, 30). But what is 13 here? 
```
results = np.zeros((13, len(MC_stochastic)))
for idx,samples  in enumerate(MC_stochastic):
    results[:, idx] = uncertainty[str(samples)][1:14]
```

**Comment by seedatnabeel** [comment]
Hi Siva

The 13 there refers to the number of variables we need to plot the graphs in the cell below.

 MC_stochastic = [3,5,10,15,20,30], which is 6 different number of MC samples. For each we compute the mean and std deviation. That gives us 12 datapoints and then the elapsed time is the 13th.

Hope that helps.

Regards
Nabeel
